{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-7.0.3.jar",
          "url": "spring-security-web-7.0.3.jar",
          "size": 928082,
          "sha512": "3dd70ffb9e7012b13e61f2d596840226a9c70d37f7ab9b2bdb83253b3b56af90bcfa530b16609b6fc91f72ae306992687faf36e4b502e319363c271cf11d52d0",
          "sha256": "76fadd577d0a3cf2af6986503b5349c651c017936591323ef761673b027400f2",
          "sha1": "097b58f6f1725417764e3ed03e73ad80a08a2d12",
          "md5": "409a501913d3b4066a0a771e7af84f42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-7.0.3.jar",
          "url": "spring-security-web-7.0.3.jar",
          "size": 928082,
          "sha512": "3dd70ffb9e7012b13e61f2d596840226a9c70d37f7ab9b2bdb83253b3b56af90bcfa530b16609b6fc91f72ae306992687faf36e4b502e319363c271cf11d52d0",
          "sha256": "76fadd577d0a3cf2af6986503b5349c651c017936591323ef761673b027400f2",
          "sha1": "097b58f6f1725417764e3ed03e73ad80a08a2d12",
          "md5": "409a501913d3b4066a0a771e7af84f42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-7.0.3-javadoc.jar",
          "url": "spring-security-web-7.0.3-javadoc.jar",
          "size": 1942670,
          "sha512": "847ede5a3fc64fdc30d0752d176d19617c4a45cbc39eed0bc933671dc0f364b2f5491783ad21192c667b8f02e32d01c3c1ab4bd438bba18af8e99e8f5fb3cd55",
          "sha256": "aa686eab2450fd5d2a128ec85510a00db17177ed2745cb1cbc94549a076c40af",
          "sha1": "7e78657fa0fda29ea7f5209590dba7e0ec338c8f",
          "md5": "3399e625a41f788c406dc2a3c2c4b7da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-7.0.3-sources.jar",
          "url": "spring-security-web-7.0.3-sources.jar",
          "size": 755948,
          "sha512": "3546da6416bb8f75a4f681b72fa3d4cf5210e7e84153b0323b51fca3ce42162b59f41e7582c3d4cf4b4f0eaa983e88f71f1553c4e023aa29e062e09713a39b24",
          "sha256": "e0463e3e14a45614c4272fb1051f679d3fe468fbff4251d251c5f0d3905353d4",
          "sha1": "42a68ad15db5767a09c378ea79ff3d4aec406c51",
          "md5": "76ff5db5f7d1fa263a7cb2fb9799c5a8"
        }
      ]
    }
  ]
}
