{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-7.0.3.jar",
          "url": "spring-security-config-7.0.3.jar",
          "size": 2098988,
          "sha512": "741b7486091591fb165a0956c64e1c2f07f30ab45cbea20136e160b0246048faf4262aad8076d2b3e3d9c090dfded9f3a250de70b5b98e74cb0c5e8974ca8dda",
          "sha256": "82010148e845aaa346b1423bb037d34444de90b51660a35387ec271a45692295",
          "sha1": "2001d140b97c0daa8b9895d7a765d94c60733642",
          "md5": "2d2fa7c53cb8e099de7490286622162a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-7.0.3.jar",
          "url": "spring-security-config-7.0.3.jar",
          "size": 2098988,
          "sha512": "741b7486091591fb165a0956c64e1c2f07f30ab45cbea20136e160b0246048faf4262aad8076d2b3e3d9c090dfded9f3a250de70b5b98e74cb0c5e8974ca8dda",
          "sha256": "82010148e845aaa346b1423bb037d34444de90b51660a35387ec271a45692295",
          "sha1": "2001d140b97c0daa8b9895d7a765d94c60733642",
          "md5": "2d2fa7c53cb8e099de7490286622162a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-7.0.3-javadoc.jar",
          "url": "spring-security-config-7.0.3-javadoc.jar",
          "size": 1196450,
          "sha512": "c15fd8dfdf59a6b3f10df7715a7c5fdae30ab370584ad1a6302843a24549ef48dba5a778e63cf57ec0f9eb2de450e0e2df64d1c8b39ee3b79fb020f767a82561",
          "sha256": "076104dff347001cac55436e651215a75c71b1fed78d1cb976a3be90266e8e99",
          "sha1": "8703b6716dc6cc24fd8fbe45ded1cedbbe032b3e",
          "md5": "e785bfebb0950bd4a9c42c55c3a4fde5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-7.0.3-sources.jar",
          "url": "spring-security-config-7.0.3-sources.jar",
          "size": 1524723,
          "sha512": "b54349fdf77922a8ed0028d16f524fd2dc76f838f8ea504ba4ea3459cb5af956ebdb077900b6badd72857178c84b178bb803dbfe40026a2a2177492d4a919cb9",
          "sha256": "de4c5b82a481fa78ff81b32eeaffed8094ad3a56a2201df5de73e60f422a380a",
          "sha1": "78b2b9130c3751796d845758fda830bac0f10900",
          "md5": "683da1f50c7abec67b45901aea3cae53"
        },
        {
          "name": "spring-security-config-7.0.3-sources.jar",
          "url": "spring-security-config-7.0.3-sources.jar",
          "size": 1524723,
          "sha512": "b54349fdf77922a8ed0028d16f524fd2dc76f838f8ea504ba4ea3459cb5af956ebdb077900b6badd72857178c84b178bb803dbfe40026a2a2177492d4a919cb9",
          "sha256": "de4c5b82a481fa78ff81b32eeaffed8094ad3a56a2201df5de73e60f422a380a",
          "sha1": "78b2b9130c3751796d845758fda830bac0f10900",
          "md5": "683da1f50c7abec67b45901aea3cae53"
        }
      ]
    }
  ]
}
