{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-devtools",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-4.0.3.jar",
          "url": "spring-boot-devtools-4.0.3.jar",
          "size": 213407,
          "sha512": "1206e3977ab632ea73c8383a225b3323eceb5b262a273f19788de27d44d5ae4dd40d8a0f10df56c870e5bd9f940d325451617c6c2ffbcfac82f36ea36248368e",
          "sha256": "e2b0c142e2185aa86da3111b7f0f1f5682e5643ab65164a0b3d8ec225781b31f",
          "sha1": "a90e93857be2f3bedd238f961c50f473f6edda15",
          "md5": "a70d57f8c1633753ce910ce57b22d45f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-4.0.3.jar",
          "url": "spring-boot-devtools-4.0.3.jar",
          "size": 213407,
          "sha512": "1206e3977ab632ea73c8383a225b3323eceb5b262a273f19788de27d44d5ae4dd40d8a0f10df56c870e5bd9f940d325451617c6c2ffbcfac82f36ea36248368e",
          "sha256": "e2b0c142e2185aa86da3111b7f0f1f5682e5643ab65164a0b3d8ec225781b31f",
          "sha1": "a90e93857be2f3bedd238f961c50f473f6edda15",
          "md5": "a70d57f8c1633753ce910ce57b22d45f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-4.0.3-javadoc.jar",
          "url": "spring-boot-devtools-4.0.3-javadoc.jar",
          "size": 384169,
          "sha512": "b9d6064f0a280267363bd0dcde40e9d3b0d80966dfbd49d7299d7a834bd92545c422373b3ead40b4255d7d698361f8a0440c2099853f3991a2acdb639274dc5a",
          "sha256": "627b8b5498f5547b5daf8648898ef61b32850069cc4b9a2ca83031508da94d38",
          "sha1": "f60c8fd5834eb95effbded44ef59d70048cfcd0d",
          "md5": "72c170b2dcb35a473ae547f7ca1b775f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-4.0.3-sources.jar",
          "url": "spring-boot-devtools-4.0.3-sources.jar",
          "size": 141679,
          "sha512": "1f7b7c191f7efa4c592f85dc837559d4989683ad462519258aa1389a5bb90843f99614371bf87af35c92ec9246e9cd8541e01da12c62000facab53b1750901c4",
          "sha256": "8ad5338be588ca8636d73c37abca2156233ad40b03fe5c8b85b65bb0577cb800",
          "sha1": "353718d60bdb3a016efc6836a1ef15dd6077ede1",
          "md5": "fcfe4ec0699abd294cbce52acaba865f"
        }
      ]
    }
  ]
}
