{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.3.jar",
          "url": "spring-security-crypto-7.0.3.jar",
          "size": 111792,
          "sha512": "76fa6f12f5b47cb0eeb6587a1f61bdddf1fca70b2a4c8833ec70af6e7a850de95fcc33be3f6b47553e40c18ab36e2825739c217f5905e729d63ccfae29fbf84f",
          "sha256": "129e5d33c75279d40f170101f72ce0e99174bc50079615ebfccd08f26f91b00c",
          "sha1": "8d23e5e4bad2bc9a7a028e010b96ac7d6b93f6e1",
          "md5": "09f247598f6dd673cb337451502ae37c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.3.jar",
          "url": "spring-security-crypto-7.0.3.jar",
          "size": 111792,
          "sha512": "76fa6f12f5b47cb0eeb6587a1f61bdddf1fca70b2a4c8833ec70af6e7a850de95fcc33be3f6b47553e40c18ab36e2825739c217f5905e729d63ccfae29fbf84f",
          "sha256": "129e5d33c75279d40f170101f72ce0e99174bc50079615ebfccd08f26f91b00c",
          "sha1": "8d23e5e4bad2bc9a7a028e010b96ac7d6b93f6e1",
          "md5": "09f247598f6dd673cb337451502ae37c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.3-javadoc.jar",
          "url": "spring-security-crypto-7.0.3-javadoc.jar",
          "size": 265522,
          "sha512": "6d35baac34a66f4a3a84be657cf3ab1fbd6547d0cddb09e19d3e29abe47518d4482080021a73f2f7c3a41af3402876997c7de7f638ae52d06a7d9da6dd13f38d",
          "sha256": "cd928ec6b7ee3ef17fa5adc1db18acaead9e5d79ff1fe8a76c4bf674f1a429df",
          "sha1": "c1d28bc413a73c1136977a874a47d8a9c1bd936d",
          "md5": "03bfac7ebba17bf8bc87b218e395dade"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.3-sources.jar",
          "url": "spring-security-crypto-7.0.3-sources.jar",
          "size": 101552,
          "sha512": "e0131ce3832691b45f7c77b6fcae2d8ff320cd19b807058df5b4a12c81515cdb140e2d68caa19aa7ebc00f692ce19438fbc8f7387d05b5d268673c74784360a8",
          "sha256": "ff24fda3af98733ab94e33e09ade2b6ca7c2445defc12f07dd48c0daafa5d754",
          "sha1": "42869ac022963cd1c66a80dd63286755344bcd5f",
          "md5": "5882c7742706bf35f7f603b4cf48b280"
        }
      ]
    }
  ]
}
