{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-core",
    "version": "7.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-7.0.3.jar",
          "url": "spring-security-core-7.0.3.jar",
          "size": 617563,
          "sha512": "0750879d8d023ed6a58c5d3c2ef03ded785ac70935a5cca3b9a6f20ded0f7bfb8acbaef129a9c55674c35d59dc260cf2c9f2cc11ce8affb33ed8ace65e282040",
          "sha256": "4bd588eecbe728cf4d1f5920248ff9e193ad88a00c6e315423ab73e52b43a3a9",
          "sha1": "e33b3954cc47da3b99c289882d4671bed4434fbe",
          "md5": "18a56e0ca8582278ccb472b3e9a94815"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-crypto",
          "version": {
            "requires": "7.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.4"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-core-7.0.3.jar",
          "url": "spring-security-core-7.0.3.jar",
          "size": 617563,
          "sha512": "0750879d8d023ed6a58c5d3c2ef03ded785ac70935a5cca3b9a6f20ded0f7bfb8acbaef129a9c55674c35d59dc260cf2c9f2cc11ce8affb33ed8ace65e282040",
          "sha256": "4bd588eecbe728cf4d1f5920248ff9e193ad88a00c6e315423ab73e52b43a3a9",
          "sha1": "e33b3954cc47da3b99c289882d4671bed4434fbe",
          "md5": "18a56e0ca8582278ccb472b3e9a94815"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-7.0.3-javadoc.jar",
          "url": "spring-security-core-7.0.3-javadoc.jar",
          "size": 1325489,
          "sha512": "6433eca76998f9c601363f6f0643849b87bf45f68a32347a501fe0c02ac7fcd1eec61ee66fb2d3d3dfce5ddb2c1be2e22e2bba2f311119043baed859fdcaca70",
          "sha256": "189586d4fcae4168419c9f5ab23c63336c130847fff61b3c95cf9a5fc44b6bd6",
          "sha1": "e47d4cc24fd166effae1d760a696de80e9021942",
          "md5": "433d5cb55bc4a37ac747e0e8bef111b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-core-7.0.3-sources.jar",
          "url": "spring-security-core-7.0.3-sources.jar",
          "size": 550729,
          "sha512": "2bfe0ba058188a04dcc2962caf7a86451adaf45be1933cb083732757c9aa6d54b0831f81774558eed0deba24071c9fe69b46ecfa46782d7b56b48fb2cc653553",
          "sha256": "5f1885c0e89875927a56eeee3accd98e0048f144281a4bb38e051e1605ac4a96",
          "sha1": "860204d226aff326ceb064a4716a8de0d8ed3b4f",
          "md5": "c9440a96626a1dbb9ba181f3cef4689a"
        },
        {
          "name": "spring-security-core-7.0.3-sources.jar",
          "url": "spring-security-core-7.0.3-sources.jar",
          "size": 550729,
          "sha512": "2bfe0ba058188a04dcc2962caf7a86451adaf45be1933cb083732757c9aa6d54b0831f81774558eed0deba24071c9fe69b46ecfa46782d7b56b48fb2cc653553",
          "sha256": "5f1885c0e89875927a56eeee3accd98e0048f144281a4bb38e051e1605ac4a96",
          "sha1": "860204d226aff326ceb064a4716a8de0d8ed3b4f",
          "md5": "c9440a96626a1dbb9ba181f3cef4689a"
        }
      ]
    }
  ]
}
